name: "AWS Marketplace | Mirror: Optimize"

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag for the optimize image"
        required: true
        type: string

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/aws-marketplace-ecr-login
        with:
          aws-role-arn: "arn:aws:iam::${{ secrets.DISTRO_CI_AWS_MPLACE_AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction"
          aws-region: "us-east-1"
          
      - name: mirror optimize
        uses: ./.github/actions/aws-marketplace-ecr-mirror
        with:
          from: camunda/optimize:${{ inputs.imageTag }}
          to: ${{ env.MARKETPLACE_BASE_URL }}/camunda/camunda8/optimize:${{ inputs.imageTag }}
