name: "AWS Marketplace | Mirror: Operate"

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag for the Camunda images"
        required: true
        type: string

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/aws-marketplace-ecr-login
        with:
          aws-role-arn: "arn:aws:iam::${{ secrets.DISTRO_CI_AWS_MPLACE_AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction"
          aws-region: "us-east-1"

      - name: mirror operate
        uses: ./.github/actions/aws-marketplace-ecr-mirror
        with:
          from: camunda/operate:${{ inputs.imageTag }}
          to: ${{ env.MARKETPLACE_BASE_URL }}/camunda/camunda8/operate:${{ inputs.imageTag }}
