name: "AWS Marketplace | Mirror: Connectors"

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag for the connectors image"
        required: true
        type: string

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ./.github/actions/aws-marketplace-ecr-login
        with:
          aws-role-arn: "arn:aws:iam::${{ secrets.DISTRO_CI_AWS_MPLACE_AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction"
          aws-region: "us-east-1"
          aws-marketplace-base-url: ${{ secrets.DISTRO_CI_AWS_MPLACE_BASE_URL }}

      - name: mirror connectors
        uses: ./.github/actions/aws-marketplace-ecr-mirror
        with:
          from: camunda/connectors-bundle:${{ inputs.imageTag }}
          to: ${{ secrets.DISTRO_CI_AWS_MPLACE_BASE_URL }}/camunda/camunda8/connectors-bundle:${{ inputs.imageTag }}
