name: "Docker Compose | Test - E2E - Full Setup"
on:
  push:
    branches:
      - main
    paths:
      - docker-compose/versions/**
  pull_request:
    paths:
      - .github/workflows/docker-compose-test-e2e-template.yaml
      - .github/workflows/docker-compose-test-e2e-full-setup.yaml
      - docker-compose/versions/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  init:
    name: Generate version matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Generate versions
        id: generate-versions-matrix
        uses: ./.github/actions/generate-versions-matrix
        with:
          versions-path: "docker-compose/versions/camunda-8.*"
    outputs:
      unchanged-versions: ${{ steps.generate-versions-matrix.outputs.unchanged }}

  exec:
    needs: [init]
    name: ${{ matrix.versions.name }}
    strategy:
      fail-fast: false
      matrix:
        versions:
          # Camunda 8.3
          - name: Camunda 8.3 ⭐
            camunda-version: "8.3"
            main-compose-args: "-f docker-compose.yaml"
            e2e-test-enabled: false
          - name: Camunda 8.3 - Identity Disabled
            camunda-version: "8.3"
            main-compose-args: "-f docker-compose-core.yaml"
            e2e-test-enabled: false
          # Camunda 8.4
          - name: Camunda 8.4 ⭐
            camunda-version: "8.4"
            main-compose-args: "-f docker-compose.yaml"
            e2e-test-enabled: false
          - name: Camunda 8.4 - Identity Disabled
            camunda-version: "8.4"
            main-compose-args: "-f docker-compose-core.yaml"
            e2e-test-enabled: false
          # Camunda 8.5
          - name: Camunda 8.5 ⭐
            camunda-version: "8.5"
            main-compose-args: "-f docker-compose.yaml"
            e2e-test-enabled: false
          - name: Camunda 8.5 - Identity Disabled
            camunda-version: "8.5"
            main-compose-args: "-f docker-compose-core.yaml"
            e2e-test-enabled: false
          # Camunda 8.6
          - name: Camunda 8.6 ⭐
            camunda-version: "8.6"
            e2e-test-enabled: true
          - name: Camunda 8.6 - Identity Disabled
            camunda-version: "8.6"
            main-compose-args: "-f docker-compose-core.yaml"
            e2e-test-enabled: false
          - name: Camunda 8.6 - Web Modeler Standalone
            camunda-version: "8.6"
            main-compose-args: "-f docker-compose-web-modeler.yaml"
            e2e-test-enabled: false
          # Camunda 8.7
          - name: Camunda 8.7 ⭐
            camunda-version: "8.7"
            main-compose-args: "-f docker-compose.yaml"
            e2e-test-enabled: true
          - name: Camunda 8.7 - Identity Disabled
            camunda-version: "8.7"
            main-compose-args: "-f docker-compose-core.yaml"
            e2e-test-enabled: false
          - name: Camunda 8.7 - Web Modeler Standalone
            camunda-version: "8.7"
            main-compose-args: "-f docker-compose-web-modeler.yaml"
            e2e-test-enabled: false
#           # Camunda Alpha
#           - name: Camunda Alpha ⭐
#             camunda-version: "alpha"
#             main-compose-args: "-f docker-compose.yaml"
#             e2e-test-enabled: true
#           - name: Camunda Alpha - Identity Disabled
#             camunda-version: "alpha"
#             main-compose-args: "-f docker-compose-core.yaml"
#             e2e-test-enabled: false
#           - name: Camunda Alpha - Web Modeler Standalone
#             camunda-version: "alpha"
#             main-compose-args: "-f docker-compose-web-modeler.yaml"
#             e2e-test-enabled: false
        exclude: ${{ fromJson(needs.init.outputs.unchanged-versions) }}
    uses: ./.github/workflows/docker-compose-test-e2e-template.yaml
    secrets: inherit
    with:
      camunda-version: ${{ matrix.versions.camunda-version }}
      deps-compose-args: ${{ matrix.versions.deps-compose-args }}
      main-compose-args: ${{ matrix.versions.main-compose-args }}
      e2e-test-enabled: ${{ matrix.versions.e2e-test-enabled }}
